name: build it

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Build with Maven
      run: |
        curl https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.18/lombok-1.18.18.jar -o lombok.jar
        export MAVEN_OPTS=-javaagent:lombok.jar
        mvn clean verify --batch-mode ${{ inputs.mvnArgs }} ${{ secrets.mvnArgs }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: |
          */target/*-reports/*.xml
          !*/target/*-reports/failsafe-summary.xml

    - name: Archive build artifact
      uses: actions/upload-artifact@v2
      with:
        path: |
          */target/*.iar
          *product/target/*.zip
